### PR TITLE
Destroy tab if blank when clicking on icon

### PR DESCRIPTION
**Pull request by DanielBreiner**
#28

### CODE REVIEW

**Comment by keombre** [comment]
Hi! Thank's for your contribution.

The feature looks good, but I don't like the fact that you are creating a new tab and then destroying the empty one.
Maybe `chrome.tabs.update` could be used for this purpose.

**Comment by DanielBreiner** [comment]
Heyo.

> The feature looks good, but I don't like the fact that you are creating a new tab and then destroying the empty one.
Maybe chrome.tabs.update could be used for this purpose.

Yeah, I couldn't figure out how to do so without having the dropdown open. If you're ok with that, I can change the code to use `chrome.tabs.update`. Otherwise feel free to close the PR and give it a try yourself. I don't have much experience with browser extensions. Sorry about that.

Cheers.

**Comment by keombre** [comment]
Hi!

>  I couldn't figure out how to do so without having the dropdown open.

That popup is just another web page. It can be closed with `window.close()`.

> I don't have much experience with browser extensions. Sorry about that.

Don't worry, it's great that you want to help and the fact, that you had the stomach to poke into this mess-of-a-project is admirable.

Push the `tabs.update` and `window.close` and I'l merge this ;-)

*edit: now that I'm thinking about this, we'll just open and close a different tab :D
However, opening and closing tat popup should lead to better user experience since the popup doesn't have enough time to "pop-up". Thus not distracting the user.

**Comment by DanielBreiner** [comment]
Awesome, thanks a lot for the help.

**Pull request merged**
